env:
  name: "toy"
agent:
  lr: 1e-3
  gamma: 0.99
  batch_size: 64
train:
  episodes: 1000
  target_update: 10
  replay_capacity: 50000
explore:
  epsilon_start: 1.0
  epsilon_end: 0.05
  epsilon_decay: 500