name: CI

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Lint with black & flake8
        run: |
          pip install black flake8
          black --check .
          flake8 .
      - name: Run Tests
        run: pytest --maxfail=1 --disable-warnings -q